name: CI

on: 
  push: 
    branches: [ "main" ]
  pull_request: 		
    branches: [ "main" ]
  
  workflow_dispatch:
  
jobs: 
  CI: 
    runs-on: ubuntu-latest
      
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v3
          
      - name: teste pipeline
        run: echo "teste githubactions"
        
        
